### ISSUE TITLE
$SqlConnection.ServiceInstanceId is null

### ISSUE THREAD

**Issue by rkasavaraju** [Apocrathia/DISA-SQL-2014-STIG#1]
filename: sqlstig.psm1 

Line 788
I had to change
} -ArgumentList @($SqlConnection.ServiceInstanceId, $Enable, $PassThru) 
to
} -ArgumentList @($SqlConnection.InstanceName, $Enable, $PassThru) 
get it working. 
write-Verbose statements inside the code block are not printing. 
Tested on SQL 2014 with Named Instance.

Line 1761
Changed AuditSpecification to ServerAuditSpecification

```
[Microsoft.SqlServer.Management.Smo.ServerAuditSpecification]$ServerAuditSpecification = New-Object  Microsoft.SqlServer.Management.Smo.ServerAuditSpecification($SqlConnection, $AuditSpecificationName)
```

**Comment by rkasavaraju** [comment]
Thank you for the STIG scripts.

**Comment by Apocrathia** [comment]
If you don't mind, submit the change as a pull request and I will get it merged in. Thanks for the correction. I know there's still some issues, but I've managed to get a system successfully through an SCA-V using this script.

**Comment by Apocrathia** [comment]
Pushed change in.

**Comment by rkasavaraju** [comment]
Thank you. Still not done with my testing. I was side tracked by other issues. at one time locked out of SQL server had to start it in single instance mode to get back in.  Still investigating..
 Thank youRamesh

```
  From: Ian <notifications@github.com>
```

 To: Apocrathia/DISA-SQL-2014-STIG DISA-SQL-2014-STIG@noreply.github.com 
Cc: RKK rkasavaraju@yahoo.com; Author author@noreply.github.com
 Sent: Friday, September 30, 2016 2:42 PM
 Subject: Re: [Apocrathia/DISA-SQL-2014-STIG] $SqlConnection.ServiceInstanceId is null (#1)

Pushed change in.—
