### ISSUE TITLE
Need help with input params

### ISSUE THREAD

**Issue by ghost** [Apocrathia/DISA-SQL-2014-STIG#2]
Set-SQLInstanceStigItems  -SqlAdministratorsName "mssqlprod" `
                        -AuditorAdministratorsName mssqlprod"`
                        -AuditorsName "mssqlprod" `
                        -ServerAuditor "mssqlprod"`
                        -DatabaseAuditor "mssqlprod" `
                        -ComputerName "localhost"`
                        -AuditDestination "ApplicationLog" `
                        -SysAdminRoleMembers @("mssqlprod")`
                        -ServerAdminRoleMembers @("mssqlprod") `
                        -DBCreatorRoleMembers @("mssqlprod")`
                        -Verbose   

Set-SQLDatabaseStigItems -ComputerName "localhost" `
                        -AllDatabases`
                        -OperatorToEmail "SQL Adminss" `
                        -MailProfile "MSSQLSERVER Profile"`
                        -Verbose

---

the following exception occurred while trying to enumerate the collection: "Failed to connect to server 

New-SQLInstanceAuditLogAccessRuleSet : Cannot bind argument to parameter 'SqlServiceAccountSid' because it is null.

Exception calling "GetParent" with "1" argument(s): "Path cannot be the empty string or all whitespace.

PLease help?

**Comment by Apocrathia** [comment]
Are you running all of this from a single command string or are you delimiting each line break with a grave?

**Comment by ghost** [comment]
i broke them out...now I have a few less errors? Can you help with these:-

VERBOSE: Creating audit specification STIG_Audit_Specification.
New-Object : A constructor was not found. Cannot find an appropriate constructor for type Microsoft.SqlServer.Management.Smo.AuditSpecification.
At C:\Users*\Documents\WindowsPowerShell\Modules\SqlStig.psm1:1740 char:179
-             [Microsoft.SqlServer.Management.Smo.AuditSpecification]$ServerAuditS ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (:) [New-Object], PSArgumentException
  - FullyQualifiedErrorId : CannotFindAppropriateCtor,Microsoft.PowerShell.Commands.NewObjectCommand

The property 'AuditName' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users*\Documents\WindowsPowerShell\Modules\SqlStig.psm1:1741 char:13
-             $ServerAuditSpecification.AuditName = $AuditName
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : PropertyNotFound

You cannot call a method on a null-valued expression.
At C:\Users*\Documents\WindowsPowerShell\Modules\SqlStig.psm1:1744 char:1
- $ServerAuditSpecification.Create()
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Cannot find path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQLServer\SuperSocketNetLib' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE...perSocketNetLib:String) [Set-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand
    + PSComputerName        : ******************

Get-Acl : Cannot find path '\*\C$\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL' because it does not exist.
At C:\Users\as021160a\Documents\WindowsPowerShell\Modules\SqlStig.psm1:5848 char:8
- $Acl = Get-Acl -Path $Path
-        ~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (:) [Get-Acl], ItemNotFoundException
  - FullyQualifiedErrorId : GetAcl_PathNotFound_Exception,Microsoft.PowerShell.Commands.GetAclCommand

**Comment by Apocrathia** [comment]
Try pulling the latest source, I just merged in a couple of changes from a previous issue that may resolve this.

Make sure your command strings look like this.

```
Set-SQLInstanceStigItems -SqlAdministratorsName "mssqlprod" `
-AuditorAdministratorsName mssqlprod" ` 
-AuditorsName "mssqlprod" `
-ServerAuditor "mssqlprod"`
-DatabaseAuditor "mssqlprod" `
-ComputerName "localhost" `
-AuditDestination "ApplicationLog" `
-SysAdminRoleMembers @("mssqlprod")`
-ServerAdminRoleMembers @("mssqlprod") `
-DBCreatorRoleMembers @("mssqlprod") `
-Verbose `
```

```
Set-SQLDatabaseStigItems -ComputerName "localhost" `
-AllDatabases `
-OperatorToEmail "SQL Admins" `
-MailProfile "MSSQLSERVER Profile" `
-Verbose `
```

**Comment by ghost** [comment]
thank you. How do I fix the custom trace events.sql? How do I run it on tables..there is no table T..in my db's

**Comment by Apocrathia** [comment]
Honestly, I haven't used the custom trace events, because there's a good bit to configure in there. Those SQL scripts are straight from DISA, and there will probably be more information in the full STIG pertaining to that. I've gotten a SQL server through an accreditation using the powershell, permissions.sql, and audit.sql scripts alone.

**Comment by ghost** [comment]
okay..I will use those. Question to your earlier response. Do I need to pull these ones again as they are updated for the powershell to run?
SqlStig.psd1  
SqlStig.psm1

**Comment by Apocrathia** [comment]
Yes.

**Comment by ghost** [comment]
okay on it, thanks

**Comment by ghost** [comment]
I re imported the modules and now I am getting the error:-
Import-Module : The specified module 'C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLPS\SQLPS.PS1' was not loaded because no valid module 
file was found in any module directory.
At C:\Users*\Desktop\DISA-SQL-2014-STIG-master\SqlStig.psm1:5623 char:13
-             Import-Module -Name "${env:ProgramFiles(x86)}\Microsoft SQL Server\$ ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ResourceUnavailable: (C:\Program File...SQLPS\SQLPS.PS1:String) [Import-Module], FileNotFoundException
  - FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by ghost** [comment]
can you please help?
Import-Module : The specified module 'C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLPS\SQLPS.PS1' was not loaded 
because no valid module file was found in any module directory.
At C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLPS\SqlStig.psm1:5623 char:13
-             Import-Module -Name "${env:ProgramFiles(x86)}\Microsoft SQL Server\$ ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ResourceUnavailable: (C:\Program File...SQLPS\SQLPS.PS1:String) [Import-Module], FileNotFoundException
  - FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by Apocrathia** [comment]
That would appear to be an issue with your system, not the code. These tickets are not for system support.

**Comment by ghost** [comment]
fine, thanks for the help.
